version: '2'
services:

 php:
  image: quentinv/phpservermonitor
  restart: always
  networks:
   - network
  ports:
   - 80:80

 mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD
     - MYSQL_DATABASE=phpservermonitor
    networks:
     - network
    restart: always

networks:
  network:
   driver: bridge
